<?php

namespace Tests\Feature;

use App\Models\Achievement;
use App\Models\Comment;
use App\Models\User;
use Database\Seeders\DatabaseSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;

class CommentTest extends TestCase
{
    use RefreshDatabase;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed();
    }

    public function test_unlocks_achievement_when_user_writes_first_comment(): void
    {

        $user = User::find(1);
        Comment::query()->create([
            'user_id' => $user->id,
            'body' => fake()->sentence()
        ]);

        $achievement = Achievement::query()
            ->where('type', 'comment')
            ->where('count', 1)->first();

        $user_achievement = $user->achievements()->latest()->first();

        $this->assertEquals($user_achievement->id, $achievement->id);

    }
}
